### ISSUE TITLE
Ошибки в консоле

### ISSUE THREAD

**Issue by kolan4ik** [yandex-maps-unofficial/vue-yandex-map#379]
Добрый день! Все работает норм но есть проблема в консоле! 

 [SSR] Error transforming node_modules/vue-yandex-maps/dist/vue-yandex-maps.esm.js: Failed to load plugin 'jest' declared in 'node_modules/vue-yandex-maps/.eslintrc.js': Cannot find module 'eslint-plugin-jest'
Require stack:
- node_modules/vue-yandex-maps/__placeholder__.js
Referenced from: node_modules/vue-yandex-maps/.eslintrc.js

  Require stack:
  - node_modules/vue-yandex-maps/__placeholder__.js
  Referenced from: node_modules/vue-yandex-maps/.eslintrc.js
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
  at Function.resolve (internal/modules/cjs/helpers.js:98:19)
  at Object.resolve (node_modules/vite-plugin-eslint/node_modules/@eslint/eslintrc/lib/shared/relative-module-resolver.js:28:50)
  at ConfigArrayFactory._loadPlugin (node_modules/vite-plugin-eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:1017:39)
  at ConfigArrayFactory._loadExtendedPluginConfig (node_modules/vite-plugin-eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:837:29)
  at ConfigArrayFactory._loadExtends (node_modules/vite-plugin-eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:779:29)
  at ConfigArrayFactory._normalizeObjectConfigDataBody (node_modules/vite-plugin-eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
  at _normalizeObjectConfigDataBody.next (<anonymous>)
  at ConfigArrayFactory._normalizeObjectConfigData (node_modules/vite-plugin-eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
  at _normalizeObjectConfigData.next (<anonymous>)

**Comment by PNKBizz** [comment]
Карта на должна подключаться на SSR

**Comment by daniluk4000** [comment]
Нативная поддержка SSR реализована в 2.0
